name: "Release"

on:
  push:
    tags:
      - v*

jobs:
  Tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: test
        run: echo "${{github.event.base_ref}}"

      - name: Exit if not on main branch
        if: endsWith(github.event.base_ref, 'master') == false
        run: exit -1

