name: "Release"

on:
  push:
    tags:
      - v*

jobs:
  Tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - run: |
        echo "${{github.ref}}"

      - name: Exit if not on main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1

